#!/bin/bash

# geckodriver
killall geckodriver
for pid in $(ps aux | grep "firefox --marionette" | sed -E 's/[^0-9]*([0-9]*).*/\1/g'); do
  echo "KILLING $pid"
  kill -9 $pid
done

# chromedriver
killall chromedriver
for pid in $(ps aux | grep "chromium" | grep " --headless" | sed -E 's/[^0-9]*([0-9]*).*/\1/g'); do
  echo "KILLING $pid"
  kill -9 $pid
done
